export const users = [
  {
    name: 'Liam Brooks',
    email: 'liam.brooks@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP201',
    department: 'Engineering',
  },
  {
    name: 'Sierra Nunez',
    email: 'sierra.nunez@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP202',
    department: 'Engineering',
  },
  {
    name: 'Noah Patel',
    email: 'noah.patel@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP203',
    department: 'Engineering',
  },
  {
    name: 'Haruto Yamamoto',
    email: 'haruto.yamamoto@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP204',
    department: 'Engineering',
  },
  {
    name: 'Kiara Osei',
    email: 'kiara.osei@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP205',
    department: 'Engineering',
  },
  {
    name: 'Felix Moreau',
    email: 'felix.moreau@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP206',
    department: 'Engineering',
  },
  {
    name: 'Elena Rossi',
    email: 'elena.rossi@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP301',
    department: 'Customer Success',
  },
  {
    name: 'Jordan Hayes',
    email: 'jordan.hayes@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP302',
    department: 'Customer Success',
  },
  {
    name: 'Maya Iqbal',
    email: 'maya.iqbal@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP303',
    department: 'Customer Success',
  },
  {
    name: 'Oliver Stone',
    email: 'oliver.stone@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP304',
    department: 'Customer Success',
  },
  {
    name: 'Zuri Coleman',
    email: 'zuri.coleman@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP305',
    department: 'Customer Success',
  },
  {
    name: 'Finn Gallagher',
    email: 'finn.gallagher@tapacademy.com',
    password: 'Password123!',
    role: 'employee',
    employeeId: 'EMP306',
    department: 'Engineering',
  },
  {
    name: 'Amelia Grant',
    email: 'amelia.grant@tapacademy.com',
    password: 'Password123!',
    role: 'manager',
    employeeId: 'MGR301',
    department: 'Engineering',
  },
  {
    name: 'Darius Cole',
    email: 'darius.cole@tapacademy.com',
    password: 'Password123!',
    role: 'manager',
    employeeId: 'MGR302',
    department: 'Customer Success',
  },
]
